apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: alpine-dev
spec:
  failedBuildsHistoryLimit: 3
  output:
    to:
      kind: ImageStreamTag
      name: alpine-dev:latest
  source:
    type: Git
    contextDir: /
    git:
      uri: https://github.com/larsks/alpine-dev-image
      ref: main
  strategy:
    dockerStrategy:
      dockerfilePath: Containerfile
    type: Docker
  successfulBuildsHistoryLimit: 3
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secretReference:
        name: github-buildconfig
